#include <algorithm>
#include <array>
#include <atomic>
#include <cerrno>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <memory>
#include <iterator>
#include <cctype>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include <alsa/asoundlib.h>
#include <libusb-1.0/libusb.h>
#include "remold/protocol.hpp"
#include "remold/unix_socket.hpp"
using namespace remold;
namespace {
std::atomic<bool> run{true};void stoph(int){run=false;}
#pragma pack(push,1)
struct BootCommand{uint32_t magic,tag,bytes,command,address,unknown;};struct BootStatus{uint32_t magic,tag,status;};
#pragma pack(pop)
constexpr uint32_t CMDMAG=0x06022009u,STATMAG=0x0A6FE000u,LOAD=0x00080000u,ENTRY=0x00080030u;constexpr uint16_t VID=0x045e,BOOTPID=0x02ad,RUNPID=0x02bb;
struct Diag{std::atomic<uint64_t> usbOpen{0},bootSessions{0},runtimeSessions{0},fwUploads{0},fwFailures{0},alsaReads{0},published{0},clients{0};std::mutex m;std::string stage="starting",detail="";int last=0;
 void set(std::string s,int e=0,std::string d=""){{std::lock_guard<std::mutex>g(m);stage=std::move(s);last=e;detail=std::move(d);}write();}
 void write(){std::string s,d;int e;{std::lock_guard<std::mutex>g(m);s=stage;d=detail;e=last;}std::filesystem::create_directories(kRuntimeDir);std::ostringstream o;o<<"version=12\nheartbeat_ms="<<unixio::monotonic_ms()<<"\naudio_transport_model=libusb-boot-uac-runtime-alsa\nboot_usb_pid=02ad\nruntime_usb_pid=02bb\nruntime_capture=alsa-hw\nraw_audio_pipe=Kinect360RemoldAudio\nraw_audio_bus_mode=multi-client\nfirmware_kind=Microsoft-Kinect-SDK-UACFirmware\nstage="<<s<<"\ndetail="<<d<<"\nlast_error="<<e<<"\nusb_open_attempts="<<usbOpen.load()<<"\nboot_sessions="<<bootSessions.load()<<"\nruntime_sessions="<<runtimeSessions.load()<<"\nfirmware_uploads="<<fwUploads.load()<<"\nfirmware_failures="<<fwFailures.load()<<"\nalsa_reads="<<alsaReads.load()<<"\nwasapi_packets="<<alsaReads.load()<<"\nwasapi_frames="<<(published.load()*audio::kSamples)<<"\ncapture_sample_rate=16000\ncapture_channels=4\ncapture_bits=32\npublished_frames="<<published.load()<<"\npipe_clients="<<clients.load()<<"\n";std::string tmp=std::string(kAudioStatus)+".tmp";{std::ofstream f(tmp);f<<o.str();}std::error_code ec;std::filesystem::rename(tmp,kAudioStatus,ec);if(ec){std::filesystem::remove(kAudioStatus,ec);std::filesystem::rename(tmp,kAudioStatus,ec);}}
}diag;
class Fanout{public:explicit Fanout(const char*p):path_(p){}~Fanout(){stop();}bool start(){s_=unixio::server_socket(path_,0666);if(s_<0)return false;t_=std::thread([this]{accept_loop();});return true;}void stop(){stopping_=true;if(s_>=0){::shutdown(s_,SHUT_RDWR);::close(s_);s_=-1;}if(t_.joinable())t_.join();std::lock_guard<std::mutex>g(m_);for(int c:clients_)::close(c);clients_.clear();::unlink(path_.c_str());}void publish(const int32_t*p,uint64_t frame){audio::FrameHeader h{};h.channelMask=0xF;h.frameNumber=frame;h.tickMs=unixio::monotonic_ms();std::lock_guard<std::mutex>g(m_);for(auto it=clients_.begin();it!=clients_.end();){if(!unixio::write_all(*it,&h,sizeof(h))||!unixio::write_all(*it,p,audio::kPayloadBytes)){::close(*it);it=clients_.erase(it);diag.clients.fetch_sub(1);}else ++it;}}
private:std::string path_;int s_=-1;std::thread t_;std::atomic<bool>stopping_{false};std::mutex m_;std::vector<int>clients_;void accept_loop(){while(!stopping_&&run){int c=::accept4(s_,nullptr,nullptr,SOCK_CLOEXEC);if(c<0){if(errno==EINTR)continue;if(stopping_)break;continue;}audio::Request q{};audio::Reply r{};if(!unixio::read_exact(c,&q,sizeof(q))||q.magic!=audio::kMagic||q.version!=audio::kVersion||q.command!=audio::Command::SubscribeMicrophones){::close(c);continue;}if(!unixio::write_all(c,&r,sizeof(r))){::close(c);continue;}std::lock_guard<std::mutex>g(m_);clients_.push_back(c);diag.clients.fetch_add(1);}}};
struct UsbBoot{libusb_device_handle*h=nullptr;int iface=-1,alt=0;uint8_t in=0x81,out=0x01;~UsbBoot(){if(h){if(iface>=0)libusb_release_interface(h,iface);libusb_close(h);}}};
std::unique_ptr<UsbBoot> open_boot(libusb_context*ctx){diag.usbOpen.fetch_add(1);libusb_device_handle*h=libusb_open_device_with_vid_pid(ctx,VID,BOOTPID);if(!h)return {};auto s=std::make_unique<UsbBoot>();s->h=h;libusb_device*dev=libusb_get_device(h);libusb_config_descriptor*cfg=nullptr;if(libusb_get_active_config_descriptor(dev,&cfg)!=0&&libusb_get_config_descriptor(dev,0,&cfg)!=0)return {};for(uint8_t i=0;i<cfg->bNumInterfaces&&s->iface<0;i++)for(int a=0;a<cfg->interface[i].num_altsetting;a++){auto&alt=cfg->interface[i].altsetting[a];bool hi=false,ho=false;for(uint8_t e=0;e<alt.bNumEndpoints;e++){auto&ep=alt.endpoint[e];if((ep.bmAttributes&3)!=LIBUSB_TRANSFER_TYPE_BULK)continue;if(ep.bEndpointAddress==0x81)hi=true;if(ep.bEndpointAddress==0x01)ho=true;}if(hi&&ho){s->iface=alt.bInterfaceNumber;s->alt=alt.bAlternateSetting;break;}}libusb_free_config_descriptor(cfg);if(s->iface<0)return {};if(libusb_kernel_driver_active(h,s->iface)==1)libusb_detach_kernel_driver(h,s->iface);if(libusb_claim_interface(h,s->iface)!=0)return {};if(s->alt&&libusb_set_interface_alt_setting(h,s->iface,s->alt)!=0)return {};return s;}
bool bulk_write(UsbBoot&s,const void*p,int n){int x=0;return libusb_bulk_transfer(s.h,s.out,(unsigned char*)const_cast<void*>(p),n,&x,3000)==0&&x==n;}bool bulk_read(UsbBoot&s,void*p,int n){int x=0;return libusb_bulk_transfer(s.h,s.in,(unsigned char*)p,n,&x,3000)==0&&x==n;}bool status(UsbBoot&s,uint32_t tag){BootStatus st{};return bulk_read(s,&st,sizeof(st))&&st.magic==STATMAG&&st.tag==tag&&st.status==0;}
bool upload(UsbBoot&s,const std::vector<uint8_t>&fw){uint32_t tag=1;BootCommand probe{CMDMAG,tag,0x60,0,0x15,0};std::array<uint8_t,0x60>vr{};if(!bulk_write(s,&probe,sizeof(probe))||!bulk_read(s,vr.data(),vr.size())||!status(s,tag))return false;tag++;uint32_t addr=LOAD;for(size_t off=0;off<fw.size()&&run;){uint32_t page=std::min<size_t>(16*1024,fw.size()-off);BootCommand c{CMDMAG,tag,page,3,addr,0};if(!bulk_write(s,&c,sizeof(c)))return false;for(uint32_t po=0;po<page;){uint32_t ch=std::min<uint32_t>(512,page-po);if(!bulk_write(s,fw.data()+off+po,ch))return false;po+=ch;}if(!status(s,tag))return false;off+=page;addr+=page;tag++;}BootCommand launch{CMDMAG,tag,0,4,ENTRY,0};if(!bulk_write(s,&launch,sizeof(launch)))return false;BootStatus st{};if(bulk_read(s,&st,sizeof(st)))return st.magic==STATMAG&&st.tag==tag&&st.status==0;return true;}
bool usb_parent_matches(const std::filesystem::path&p){std::error_code ec;auto cur=std::filesystem::canonical(p,ec);if(ec)return false;for(int i=0;i<8&&!cur.empty();i++,cur=cur.parent_path()){std::ifstream v(cur/"idVendor"),d(cur/"idProduct");std::string vs,ds;if(v>>vs&&d>>ds)return vs=="045e"&&ds=="02bb";}return false;}
std::string find_pcm(){std::error_code ec;std::filesystem::directory_iterator it("/sys/class/sound",ec),end;if(ec)return {};for(;it!=end;it.increment(ec)){if(ec){ec.clear();continue;}const auto&e=*it;auto n=e.path().filename().string();if(n.rfind("card",0)!=0)continue;std::string num=n.substr(4);if(num.empty()||!std::all_of(num.begin(),num.end(),[](unsigned char c){return std::isdigit(c)!=0;}))continue;if(!usb_parent_matches(e.path()/"device"))continue;for(int dev=0;dev<4;dev++){std::string name="hw:"+num+","+std::to_string(dev);snd_pcm_t*p=nullptr;if(snd_pcm_open(&p,name.c_str(),SND_PCM_STREAM_CAPTURE,SND_PCM_NONBLOCK)==0){snd_pcm_close(p);return name;}}}return {};}
int capture(const std::string&name,Fanout&a){snd_pcm_t*pcm=nullptr;int rc=snd_pcm_open(&pcm,name.c_str(),SND_PCM_STREAM_CAPTURE,0);if(rc<0)return rc;snd_pcm_hw_params_t*hw;snd_pcm_hw_params_alloca(&hw);snd_pcm_hw_params_any(pcm,hw);snd_pcm_hw_params_set_access(pcm,hw,SND_PCM_ACCESS_RW_INTERLEAVED);snd_pcm_hw_params_set_format(pcm,hw,SND_PCM_FORMAT_S32_LE);unsigned rate=16000;snd_pcm_hw_params_set_rate_near(pcm,hw,&rate,nullptr);snd_pcm_hw_params_set_channels(pcm,hw,4);snd_pcm_uframes_t period=256;snd_pcm_hw_params_set_period_size_near(pcm,hw,&period,nullptr);rc=snd_pcm_hw_params(pcm,hw);if(rc<0||rate!=16000){snd_pcm_close(pcm);return rc<0?rc:-EINVAL;}diag.runtimeSessions.fetch_add(1);diag.set("uac-runtime-capturing",0,name);std::vector<int32_t>buf(audio::kChannels*audio::kSamples);uint64_t frame=0;while(run){snd_pcm_sframes_t n=snd_pcm_readi(pcm,buf.data(),audio::kSamples);if(n==-EPIPE){snd_pcm_prepare(pcm);continue;}if(n<0){rc=n;break;}diag.alsaReads.fetch_add(1);if(n!=audio::kSamples)continue;a.publish(buf.data(),++frame);diag.published.fetch_add(1);if((frame%30)==0)diag.write();}snd_pcm_close(pcm);return rc;}
std::vector<uint8_t> read_fw(){std::ifstream f(kFirmwarePath,std::ios::binary);if(!f)return {};std::vector<uint8_t> out;char c;while(f.get(c))out.push_back(static_cast<uint8_t>(c));return out;}
}
int main(){std::signal(SIGINT,stoph);std::signal(SIGTERM,stoph);std::signal(SIGPIPE,SIG_IGN);Fanout monitor(kAudioSocket);if(!monitor.start())return 2;libusb_context*ctx=nullptr;if(libusb_init(&ctx)!=0)return 3;while(run){auto pcm=find_pcm();if(!pcm.empty()){capture(pcm,monitor);unixio::retry_sleep(500);continue;}auto fw=read_fw();if(fw.empty()){diag.set("uac-firmware-missing",ENOENT,kFirmwarePath);unixio::retry_sleep(1500);continue;}auto boot=open_boot(ctx);if(boot){diag.bootSessions.fetch_add(1);diag.set("uac-firmware-uploading");if(upload(*boot,fw)){diag.fwUploads.fetch_add(1);diag.set("uac-firmware-launched");unixio::retry_sleep(1500);}else{diag.fwFailures.fetch_add(1);diag.set("uac-firmware-error",EIO);unixio::retry_sleep(750);}continue;}diag.set("uac-endpoint-not-found",ENODEV);unixio::retry_sleep(750);}libusb_exit(ctx);return 0;}
